# usage:
#
# $ compose pull && \
#   NETFOUNDRY_API_ACCOUNT=~/.netfoundry/credentials.json \
#   NETFOUNDRY_DOWNLOADED_NETWORK=~/Downloads/downloaded_network.yml \
#     docker-compose run network_from_download
#
# or
#
# $ docker-compose pull && \
#   NETFOUNDRY_API_ACCOUNT=~/.netfoundry/credentials.json \
#   NETFOUNDRY_ANSIBLE_PLAYBOOK=~/Downloads/playbook.yml \
#     docker-compose run run_playbook
#

version: '3.3'
services:
  network_from_download:
    image: netfoundry/ansible:latest
    build:
      context: .
    volumes:
      - ${NETFOUNDRY_API_ACCOUNT:-~/.netfoundry/credentials.json}:/netfoundry/credentials.json
      - ${NETFOUNDRY_DOWNLOADED_NETWORK:-~/Downloads/downloaded_network.yml}:/netfoundry/downloaded_network.yml
    command: ansible-playbook netfoundry.platform.network_from_download
  run_playbook:
    image: netfoundry/ansible:latest
    build:
      context: .
    volumes:
      - ${NETFOUNDRY_API_ACCOUNT:-~/.netfoundry/credentials.json}:/netfoundry/credentials.json
      - ${NETFOUNDRY_ANSIBLE_PLAYBOOK:-~/Downloads/playbook.yml}:/netfoundry/playbook.yml
    command: ansible-playbook /netfoundry/playbook.yml
