
- hosts: localhost
  collections:
  - netfoundry.platform
  - community.general
  tasks:
  - name: Establish session and discover Network
    netfoundry_info:
      network: BibbidiBobbidiBoo
      credentials: credentials.json
    register: netfoundry_info

  - name: Read Services from CSV file
    read_csv:
        path: services.csv
    register: services

  # where headings are serviceNumber	serviceName	attribute	ipAddress	port	hostName	edgeRouterId
  - name: declare Services from CSV
    netfoundry_service:
      network: "{{ netfoundry_info.network }}"
      name: "{{ item.serviceName }}"
      attributes: 
      - "{{ item.attribute }}"
      clientHostName: "{{ item.hostName }}"
      clientPortRange: "{{ item.port }}"
      egressRouter: "{{ item.edgeRouterId }}"
      serverHostName: "{{ item.ipAddress }}"
      serverPortRange: "{{ item.port }}"
      serverProtocol: TCP
    loop: "{{ services.list }}"
    register: services_loop

  - name: print failed results
    debug:
      msg: "{{ item }}"
    loop: "{{ services_loop.results }}"
#    when: item.
#    when: item.serviceNumber|int < 4
     
#   - name: delete Services
#     netfoundry_service:
#       network: "{{ netfoundry_info.network }}"
#       name: "{{ item.serviceName }}"
#       state: DELETED
#     loop: "{{ services.list }}"
#     when: item.serviceNumber|int > 3
