version: "3.3"
services:
    dialer:
        image: docker.io/netfoundry/ziti-tunnel:tproxy
        volumes:
        - ~/netfoundry:/netfoundry
        network_mode: host
        cap_add:
        - NET_ADMIN
        environment:
        - NF_REG_NAME
        - PFXLOG_NO_JSON=true
        command: tproxy --resolver udp://127.0.0.123:53
    terminator:
        image: docker.io/netfoundry/ziti-tunnel:proxy
        volumes:
        - ~/netfoundry:/netfoundry
        networks:
        - netfoundry_bridge
        environment:
        - NF_REG_NAME
        - PFXLOG_NO_JSON=true
        command: proxy myExample:8080
    hello:
        image: netfoundry/railz
        ports:
        - 8888:3000
        networks:
        - netfoundry_bridge
    speedtest:
        image: mlabbe/openspeedtest
        ports:
        - 8080:8080
        networks:
        - netfoundry_bridge
networks:
    netfoundry_bridge:
