version: "3.3"
services:
    builder:
        image: netfoundry/python:demo
        restart: "no"
        volumes:
        - .:/netfoundry
        environment:
        - NETFOUNDRY_API_ACCOUNT
        - NETWORK_NAME
        command: python3 -m netfoundry.demo ${NETWORK_NAME} privateServices
    dialer:
        image: docker.io/netfoundry/ziti-tunnel:tproxy
        restart: unless-stopped
        volumes:
        - .:/netfoundry
        network_mode: host
        cap_add:
        - NET_ADMIN
        environment:
        - NF_REG_NAME=dialer1
        - PFXLOG_NO_JSON=true
        command: tproxy --resolver udp://127.0.0.123:53
    exit:
        image: docker.io/netfoundry/ziti-tunnel:tun
        restart: unless-stopped
        volumes:
        - .:/netfoundry
        networks:
        - netfoundry_bridge
        cap_add:
        - NET_ADMIN
        environment:
        - NF_REG_NAME=exit1
        - PFXLOG_NO_JSON=true
        devices:
        - "/dev/net/tun:/dev/net/tun"
        command: tun --resolver none
    hello:
        image: netfoundry/railz
        restart: "no"
        ports:
        - 3000:3000
        networks:
        - netfoundry_bridge
    httpbin:
        image: kennethreitz/httpbin
        restart: "no"
        ports:
        - 8081:80
        networks:
        - netfoundry_bridge

networks:
    netfoundry_bridge:
