version: "3.3"
services:
    client:
        image: docker.io/netfoundry/ziti-tunnel:latest
        restart: unless-stopped
        volumes:
        - .:/netfoundry
        network_mode: host
        cap_add:
        - NET_ADMIN
        environment:
        - NF_REG_NAME=Linux1
        - PFXLOG_NO_JSON=true
        command: tproxy --resolver udp://127.0.0.123:53 # configure as first nameserver on Linux device to use client
    exit:
        image: docker.io/netfoundry/ziti-tunnel:latest
        restart: unless-stopped
        volumes:
        - .:/netfoundry
        cap_add:
        - NET_ADMIN
        environment:
        - NF_REG_NAME=Exit1
        - PFXLOG_NO_JSON=true
        command: host
    hello:
        image: netfoundry/hello-world-webpage
        restart: "no"
        ports:
        - 3000:80
    httpbin:
        image: kennethreitz/httpbin
        restart: "no"
        ports:
        - 8081:80

