
- hosts: localhost
  collections:
  - qrkourier.netfoundry
  tasks:
  - name: find Network resources
    netfoundry_info:
      networkName: BibbidiBobbidiBoo
      credentials: credentials.json # relative to playbook
    register: netfoundry_info
  - name: dump output
    debug:
      msg: "{{ netfoundry_info }}"
  - name: show Organization
    debug:
      msg: "{{ netfoundry_info.organization }}"
  - name: list Endpoint names
    debug:
      msg: "* {{ item.name }}"
    loop: "{{ netfoundry_info.endpoints }}"

  #   - name: create Endpoint
  #     uri:
  #       url: "https://gateway.production.netfoundry.io/core/v2/endpoints"
  #       body_format: json
  #       method: POST
  #       headers:
  #           Content-Type: application/json
  #           Authorization: Bearer {{lookup('env', 'NETFOUNDRY_API_TOKEN')}}
  #       body:
  #           networkId: '{{ networkId }}'
  #           name: '{{ endpointName }}'

  # vars:
  #   networkId:
  #   endpointName: