
- hosts: localhost
  collections:
  - qrkourier.netfoundry
  tasks:
  - name: Establish session and find Network resources
    netfoundry_info:
      network: "{{ networkName }}"
      credentials: "{{ credentialsJson }}" 
    register: netfoundry_info
  - name: dump output
    debug:
      msg: "{{ netfoundry_info }}"
  - name: show Organization
    debug:
      msg: "{{ netfoundry_info.organization }}"
  - name: show Console URL
    debug:
      msg: "{{ netfoundry_info.console }}"
  - name: list Endpoint names
    debug:
      msg: "* {{ item.name }}"
    loop: "{{ netfoundry_info.endpoints }}"
  - name: create Endpoint
    netfoundry_endpoint:
      name: "{{ endpointName }}"
      state: PROVISIONED
      network: "{{ netfoundry_info.network }}"

  vars:
    networkName: BibbidiBobbidiBoo
    credentialsJson: credentials.json # relative to playbook; documentation: https://developer.netfoundry.io/v2/guides/authentication/#get-an-api-account
    endpointNames:
    - dialer1
    - exit1
