---

  # declare entities from a vars dict "embedded" containing the data structure
  # exported / downloaded from the NF console's "manage networks" list of
  # networks
- hosts: localhost
  gather_facts: False
  pre_tasks:
    - name: Install NetFoundry Python Package
      pip:
        name: netfoundry
      tags: pypi
  roles:
    - { role: network_from_download, tags: ['netfoundry'] }
  collections:
      - netfoundry.platform
  vars:
    # download as YAML from NF web console
    # netfoundry_downloaded_network: /netfoundry/downloaded_network.yml
    # netfoundry_credentials: /netfoundry/credentials.json
