
- hosts: all
  tasks:
    - name: create Endpoint
      uri:
        url: "https://gateway.production.netfoundry.io/core/v2/endpoints"
        body_format: json
        method: POST
        headers:
            Content-Type: application/json
            Authorization: Bearer {{lookup('env', 'NETFOUNDRY_API_TOKEN')}}
        body:
            networkId: '{{ networkId }}'
            name: '{{ endpointName }}'

  vars:
    networkId:
    endpointName: