
- hosts: localhost
  collections:
  - qrkourier.netfoundry
  tasks:
  - name: Establish session and find Network resources
    netfoundry_info:
      network: "{{ networkName }}"
      credentials: "{{ credentialsJson }}" 
    register: netfoundry_info
  - name: show Organization
    debug:
      msg: "{{ netfoundry_info.organization }}"
  - name: show Console URL
    debug:
      msg: "{{ netfoundry_info.console }}"
  - name: list Endpoint names
    debug:
      msg: "NAME: {{ item.name }}"
    loop: "{{ netfoundry_info.endpoints }}"
  - name: create Endpoint
    netfoundry_endpoint:
      name: "{{ item }}"
      state: PROVISIONED
      network: "{{ netfoundry_info.network }}"
      attributes:
      - "#dialers"
      dest: /tmp/netfoundry                  # filename is Endpoint name if dest is a directory
      #dest: /tmp/netfoundry/ott-{{item}}.jwt # custom filename if name is like *.jwt
    loop: "{{ endpointNames }}"
    when: item not in netfoundry_info.endpoints|map(attribute='name')|list
  #  debugger: on_failed
  # - name: Delete all Endpoints
  #   netfoundry_endpoint:
  #     name: "{{ item }}"
  #     state: DELETED
  #     network: "{{ netfoundry_info.network }}"
  #   loop: "{{ netfoundry_info.endpoints|map(attribute='name')|list }}"

  vars:
    networkName: kentest1209
    credentialsJson: nfint-ZitiBastions.json # relative to playbook; documentation: https://developer.netfoundry.io/v2/guides/authentication/#get-an-api-account
    endpointNames:
    - dialer1
    - exit1
