---
name: Build Collection for Galaxy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build Collection and Publish to Galaxy
        #uses: docker://ghcr.io/artis3n/ansible_galaxy_collection@v2.4.2
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          collection_dir: 'netfoundry.platform'
          publish: false
